#!/bin/bash

exp_name=$1
cluster_list=$2
categories_file=$3
base_img_path=$4

#question builder for Derry's experiment with clusters

rm -rf $exp_name
mkdir $exp_name
mkdir $exp_name/images

n=0

while read line; do

	read category1 verb category2 <<< $(echo "$line" | cut -f2 | sed 's/_/ /' | rev | sed 's/_/ /' | rev)

	category1_engname=$(cat $categories_file | grep -i ^$category1, | cut -f2 -d',') 
	category2_engname=$(cat $categories_file | grep -i ^$category2, | cut -f2 -d',')
	verb_trim=$(echo $verb | tr '_' ' ')
	
	question=$(echo -e "Is it interesting for NELL to learn about $category2_engname that $category1_engname can $verb_trim? * *A) yes, very much *B) yes, it is *C) whatever *D) not really *E) I didn't understand that")

	echo "$question"

	java -jar bin/img-creator.jar $base_img_path "$question"

	mv output_image.png $exp_name/images/question$n
	readlink -f $exp_name/images/question$n >> $exp_name/img_path_file

	let "n++"

done < $cluster_list

tar cfv images.tar.gz $exp_name/images

mv images.tar.gz $exp_name
mv $cluster_list $exp_name
